<?php

namespace AppBundle\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function getUserCategories($userId)
    {
        return $this->getEntityManager()
            ->createQuery('
                SELECT c
                FROM AppBundle:Category c
                WHERE c.userId = :userId
            ')
            ->setParameter('userId', $userId)
            ->getArrayResult()
            ;
    }

    public function getCategoryByIdAndUser($id, $userId)
    {
        return $this->getEntityManager()
            ->createQuery('
                SELECT c
                FROM AppBundle:Category c
                WHERE c.id = :id and c.userId = :userId
            ')
            ->setParameter('id', $id)
            ->setParameter('userId', $userId)
            ->getOneOrNullResult()
            ;
    }

}
