<?php

namespace AppBundle\Repository;

/**
 * PhotoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhotoRepository extends \Doctrine\ORM\EntityRepository
{
    public function deletePhotoByCategoryId($categoryId)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();

        $query = $qb->delete('AppBundle:Photo', 'p')
                ->where('p.categoryId = :categoryId')
                ->setParameter('categoryId', $categoryId)
                ->getQuery();

        $query->execute();
    }

    public function getPhotoByCategoryId($categoryId)
    {
        return $this->getEntityManager()
            ->createQuery('
                SELECT p
                FROM AppBundle:Photo p
                WHERE p.categoryId = :categoryId    
            ')
            ->setParameter('categoryId', $categoryId)
            ->getArrayResult();
    }
}
